"""Write LaTeX tables for the baseline report from baselines/results/raw.json.

Usage:  python baselines/make_tables.py
Output: baselines/results/tables.tex  (\\input by baseline_report.tex)
"""
import json
from pathlib import Path

import numpy as np

RES = Path(__file__).resolve().parent / "results"

DET_NAMES = [
    ("text_sbert", "SBERT"),
    ("text_glove", "GloVe"),
    ("struct_jaccard", "Jaccard"),
    ("struct_gcn_disagree", "GCN JS"),
    ("naive_mix(sbert+gcn)", "SBERT+GCN"),
    ("naive_mix(sbert+jaccard)", "SBERT+Jacc."),
]


def ms(vals, digits=3):
    v = np.array([x for x in vals if x is not None], dtype=float)
    if not len(v):
        return "--"
    if len(v) == 1:
        return f"{v[0]:.{digits}f}"
    return f"{v.mean():.{digits}f}\\,$\\pm$\\,{v.std():.{digits}f}"


def settings(rows):
    keys = {(r["mode"], r["budget"]) for r in rows}
    return sorted(keys, key=lambda k: (k[0] != "text", k[1]))


def node_table(rows):
    out = [
        r"\begin{tabular}{llcccccc}",
        r"\toprule",
        r"Model & Attack & Acc.\,$\uparrow$ & NLL\,$\downarrow$ & ECE\,$\downarrow$ & Brier\,$\downarrow$ & Acc.\ touched & Acc.\ untouched \\",
        r"\midrule",
    ]
    clean = [r for r in rows if "mlp" in r]
    if clean:
        m = lambda k: ms(r["mlp"][k] for r in clean)
        out.append(f"MLP (no edges) & -- & {m('acc')} & {m('nll')} & {m('ece')} & {m('brier')} & -- & -- \\\\")
        out.append(r"\midrule")
    for mode, b in settings(rows):
        g = [r for r in rows if r["mode"] == mode and r["budget"] == b]
        label = "none" if b == 0 else f"{mode}, {b:.0%}".replace("%", r"\%")
        m = lambda k: ms(r["gcn"][k] for r in g)
        out.append(
            f"GCN & {label} & {m('acc')} & {m('nll')} & {m('ece')} & {m('brier')} & "
            f"{ms(r['gcn_touched_acc'] for r in g)} & {ms(r['gcn_untouched_acc'] for r in g)} \\\\"
        )
    out += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(out)


def detect_table(rows, metric):
    det = [r for r in rows if "detect" in r]
    out = [
        r"\begin{tabular}{l" + "c" * len(DET_NAMES) + "}",
        r"\toprule",
        r"& \multicolumn{2}{c}{Text only} & \multicolumn{2}{c}{Structure only} & \multicolumn{2}{c}{Naive mix} \\",
        r"\cmidrule(lr){2-3}\cmidrule(lr){4-5}\cmidrule(lr){6-7}",
        "Attack & " + " & ".join(n for _, n in DET_NAMES) + r" \\",
        r"\midrule",
    ]
    for mode, b in settings(det):
        g = [r for r in det if r["mode"] == mode and r["budget"] == b]
        vals = [np.mean([r["detect"][k][metric] for r in g]) for k, _ in DET_NAMES]
        best = max(vals)
        cells = [f"\\textbf{{{v:.3f}}}" if v == best else f"{v:.3f}" for v in vals]
        label = f"{mode}, {b:.0%}".replace("%", r"\%")
        out.append(f"{label} & " + " & ".join(cells) + r" \\")
    out += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(out)


def main():
    rows = json.loads((RES / "raw.json").read_text())
    n_splits = len({r["split"] for r in rows})
    done = len(rows)
    tex = [
        f"% generated by baselines/make_tables.py from raw.json ({done} runs, {n_splits} splits)",
        f"\\newcommand{{\\nruns}}{{{done}}}",
        f"\\newcommand{{\\nsplits}}{{{n_splits}}}",
        "\\newcommand{\\nodetable}{" + node_table(rows) + "}",
        "\\newcommand{\\aurocTable}{" + detect_table(rows, "auroc") + "}",
        "\\newcommand{\\auprcTable}{" + detect_table(rows, "auprc") + "}",
    ]
    (RES / "tables.tex").write_text("\n".join(tex) + "\n", encoding="utf8")
    print(f"wrote tables.tex from {done} runs")


if __name__ == "__main__":
    main()
